services:
  base:
    build:
      target: builder
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
      - './:/opt/chia'
  npm:
    extends:
      service: base
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
      - './:/opt/chia'
    entrypoint: 'npm'
    command: 'install'
  remix:
    extends:
      service: base
    depends_on:
      npm:
        condition: service_completed_successfully
    restart: on-failure
    environment:
      - CHIA_FULL_NODE_URL
    secrets:
      - source: full-node-cert
        target: full_node/private_full_node.crt
      - source: full-node-key
        target: full_node/private_full_node.key
    ports:
      - 3000:3000
      - 8002:8002
    command: 'remix dev'
  tailwinds:
    extends:
      service: base
    depends_on:
      npm:
        condition: service_completed_successfully
    restart: on-failure
    tty: true
    command: 'tailwindcss --watch --input ./styles/app.css --output app/styles/app.css'
secrets:
  full-node-cert:
    file: ./certs/full_node/private_full_node.crt
  full-node-key:
    file: ./certs/full_node/private_full_node.key
